package oa.codegen.created.entity;
import javax.persistence.*;
import java.util.*;
/**
*   This code is generated by FreeMarker
*   author:handong
*/
@Entity
@Table(name = "BASIC_BUSINESS")
public class ViewBus{
    /**
     *自增主键
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *使用房易贷后台的id
     */
    @Column(name="uid_fyd", length = 21, nullable = false)
    private String uid_fyd;

    /**
     *房易贷后台的进件id
     */
    @Column(name="loan_id", length = 50, nullable = false)
    private String loan_id;

    /**
     *使用OP系统的标id
     */
    @Column(name="bid_id", length = 21, nullable = false)
    private Long bid_id;

    /**
     *客户姓名
     */
    @Column(name="customer_name", length = 30, nullable = false)
    private String customer_name;

    /**
     *客户手机号码
     */
    @Column(name="telephone", length = 20, nullable = false)
    private String telephone;

    /**
     *客户身份证号码
     */
    @Column(name="id_number", length = 30, nullable = false)
    private String id_number;

    /**
     *客户申请的产品类型
     */
    @Column(name="product_type", length = 6, nullable = false)
    private String product_type;

    /**
     *
     */
    @Column(name="product_mode", length = 6, nullable = false)
    private String product_mode;

    /**
     *客户所在城市
     */
    @Column(name="city", length = 50, nullable = false)
    private String city;

    /**
     *城市编码
     */
    @Column(name="city_code", length = 6, nullable = false)
    private String city_code;

    /**
     *借款金额
     */
    @Column(name="apply_amount", length = 21, nullable = false)
    private Long apply_amount;

    /**
     *标题
     */
    @Column(name="title", length = 50, nullable = false)
    private String title;

    /**
     *客户提交申请时间
     */
    @Column(name="apply_time", length = 19, nullable = false)
    private Date apply_time;

    /**
     *关联的流程实例id
     */
    @Column(name="process_instance_id", length = 200, nullable = false)
    private String process_instance_id;

    /**
     *关联的流程定义id
     */
    @Column(name="process_definition_id", length = 200, nullable = false)
    private String process_definition_id;

    /**
     *
     */
    @Column(name="channel", length = 6, nullable = false)
    private String channel;

    /**
     *单子的状态
     */
    @Column(name="loan_status", length = 6, nullable = false)
    private String loan_status;

    /**
     *
     */
    @Column(name="apply_terms", length = 3, nullable = false)
    private Integer apply_terms;

    /**
     *1是月 2是天
     */
    @Column(name="term_type", length = 3, nullable = false)
    private Integer term_type;

    /**
     *
     */
    @Column(name="customer_email", length = 50, nullable = false)
    private String customer_email;

    /**
     *状态备注
     */
    @Column(name="status_remark", length = 40, nullable = false)
    private String status_remark;


    public ViewBus() {}


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUid_fyd() {
        return uid_fyd;
    }

    public void setUid_fyd(String uid_fyd) {
        this.uid_fyd = uid_fyd;
    }

    public String getLoan_id() {
        return loan_id;
    }

    public void setLoan_id(String loan_id) {
        this.loan_id = loan_id;
    }

    public Long getBid_id() {
        return bid_id;
    }

    public void setBid_id(Long bid_id) {
        this.bid_id = bid_id;
    }

    public String getCustomer_name() {
        return customer_name;
    }

    public void setCustomer_name(String customer_name) {
        this.customer_name = customer_name;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getId_number() {
        return id_number;
    }

    public void setId_number(String id_number) {
        this.id_number = id_number;
    }

    public String getProduct_type() {
        return product_type;
    }

    public void setProduct_type(String product_type) {
        this.product_type = product_type;
    }

    public String getProduct_mode() {
        return product_mode;
    }

    public void setProduct_mode(String product_mode) {
        this.product_mode = product_mode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCity_code() {
        return city_code;
    }

    public void setCity_code(String city_code) {
        this.city_code = city_code;
    }

    public Long getApply_amount() {
        return apply_amount;
    }

    public void setApply_amount(Long apply_amount) {
        this.apply_amount = apply_amount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getApply_time() {
        return apply_time;
    }

    public void setApply_time(Date apply_time) {
        this.apply_time = apply_time;
    }

    public String getProcess_instance_id() {
        return process_instance_id;
    }

    public void setProcess_instance_id(String process_instance_id) {
        this.process_instance_id = process_instance_id;
    }

    public String getProcess_definition_id() {
        return process_definition_id;
    }

    public void setProcess_definition_id(String process_definition_id) {
        this.process_definition_id = process_definition_id;
    }

    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public String getLoan_status() {
        return loan_status;
    }

    public void setLoan_status(String loan_status) {
        this.loan_status = loan_status;
    }

    public Integer getApply_terms() {
        return apply_terms;
    }

    public void setApply_terms(Integer apply_terms) {
        this.apply_terms = apply_terms;
    }

    public Integer getTerm_type() {
        return term_type;
    }

    public void setTerm_type(Integer term_type) {
        this.term_type = term_type;
    }

    public String getCustomer_email() {
        return customer_email;
    }

    public void setCustomer_email(String customer_email) {
        this.customer_email = customer_email;
    }

    public String getStatus_remark() {
        return status_remark;
    }

    public void setStatus_remark(String status_remark) {
        this.status_remark = status_remark;
    }

}
