package ${entity.javaPackage};
import javax.persistence.*;
import java.util.*;
/**
*   This code is generated by FreeMarker
*   generate db table to entity
*   author:handong
*/
<#list entity.annotationTypes as type >
${type.annotationInfo}
</#list>
public class ${entity.className}<#if entity.superclass?has_content> extends ${entity.superclass}</#if>{
    <#list entity.properties as property>
    ${property.comment}
    ${property.annotation}
    private ${property.propertyType} ${property.propertyName};
    private boolean isForceUpdate${property.propertyName?cap_first} = false;
    </#list>

    <#if entity.constructors>
    public ${entity.className}() {}

    </#if>

    <#--public ${entity.className}(<#list entity.properties as property>${property.javaType} ${property.propertyName}<#if property_has_next>,   ) {-->
        <#--<#list entity.properties as property>-->
            <#--this.${property.propertyName} = ${property.propertyName};-->
        <#--</#list>-->

    <#--}-->
    <#list entity.properties as property>
    public ${property.propertyType} get${property.propertyName?cap_first}() {
        return ${property.propertyName};
    }

    public void set${property.propertyName?cap_first}(${property.propertyType} ${property.propertyName}) {
        this.${property.propertyName} = ${property.propertyName};
    }

    public boolean getIsForceUpdate${property.propertyName?cap_first}() {
        return ${property.propertyName};
    }

    public ${entity.className} setIsForceUpdate${property.propertyName?cap_first}(boolean forceUpdate${property.propertyName}) {
        this.${property.propertyName} = ${property.propertyName};
        return this;
    }

    </#list>

    @Override
    public String toString() {
    return "${entity.className}{"
            <#list entity.properties as property>
                <#if property_index == 0>
                + "${property.propertyName}=" + ${property.propertyName}
                <#else >
                + ",${property.propertyName}=" + ${property.propertyName}
                </#if>
            </#list>
            + '}';
    }
}
