package ${entity.javaPackage};
import com.mossle.core.hibernate.HibernateEntityDao;
import com.souyidai.oa.persistence.ProcessNodeMsg;
import org.springframework.stereotype.Service;

/**
*   This code is generated by FreeMarker
*   author:handong
*/
<#list entity.annotationTypes as type >
${type.annotationInfo}
</#list>
public class ${entity.className}<#if entity.superclass?has_content> extends ${entity.superclass}<${entity.className}></#if>{

}
